# Generated by Django 2.0.1 on 2018-02-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offense',
            name='description',
        ),
        migrations.AddField(
            model_name='offense',
            name='ucr_name_classification',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='offense',
            name='ucr_subclass_description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
