# Generated by Django 2.0.1 on 2018-03-13 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='city',
        ),
    ]
