# Generated by Django 2.0.1 on 2018-02-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20180201_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offense',
            name='gcic_code',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='offense',
            name='ucr_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
