# Generated by Django 2.0.1 on 2018-02-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20180201_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='drivers_license',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='drivers_license_state',
            field=models.CharField(blank=True, choices=[('GA', 'Georgia')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='employer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='employer_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_employer_address', to='cases.Address'),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('BLK', 'Black'), ('BRO', 'Brown'), ('GRN', 'Green'), ('MAR', 'Maroon'), ('PNK', 'Pink'), ('BLU', 'Blue'), ('GRY', 'Gray'), ('HAZ', 'Hazel'), ('MUL', 'MUL'), ('XXX', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('BLD', 'Bald'), ('BLK', 'Black'), ('BLN', 'Blond or Strawberry'), ('BLU', 'Blue'), ('BRO', 'Brown'), ('GRY', 'Gray or Partially Gray'), ('GRN', 'Green'), ('ONG', 'Orange'), ('PNK', 'Pink'), ('PLE', 'Purple'), ('RED', 'Red or Auburn'), ('SDY', 'Sandy'), ('WHI', 'White'), ('XXX', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='home_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_party_address', to='cases.Address'),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Officer'),
        ),
    ]
