# Generated by Django 2.0.1 on 2018-02-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_auto_20180206_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='approved_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='reviewed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidentinvolvedparty',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incidentinvolvedparty',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('', '-------'), ('GA', 'Georgia')], max_length=2),
        ),
        migrations.AlterField(
            model_name='incident',
            name='shift',
            field=models.CharField(choices=[('D', 'Day'), ('E', 'Evening'), ('N', 'Night'), ('', '-------')], max_length=1),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='drivers_license_state',
            field=models.CharField(blank=True, choices=[('', '-------'), ('GA', 'Georgia')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='eye_color',
            field=models.CharField(blank=True, choices=[('BLK', 'Black'), ('BRO', 'Brown'), ('GRN', 'Green'), ('MAR', 'Maroon'), ('PNK', 'Pink'), ('BLU', 'Blue'), ('GRY', 'Gray'), ('HAZ', 'Hazel'), ('MUL', 'MUL'), ('XXX', 'Unknown'), ('', '-------')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='hair_color',
            field=models.CharField(blank=True, choices=[('BLD', 'Bald'), ('BLK', 'Black'), ('BLN', 'Blond or Strawberry'), ('BLU', 'Blue'), ('BRO', 'Brown'), ('GRY', 'Gray or Partially Gray'), ('GRN', 'Green'), ('ONG', 'Orange'), ('PNK', 'Pink'), ('PLE', 'Purple'), ('RED', 'Red or Auburn'), ('SDY', 'Sandy'), ('WHI', 'White'), ('XXX', 'Unknown'), ('', '-------')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='party_type',
            field=models.CharField(choices=[('VICTIM', 'Victim'), ('SUSPECT', 'Suspect'), ('', '-------')], max_length=7),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='race',
            field=models.CharField(choices=[('ASIAN', 'Asian'), ('BLACK', 'Black/African American'), ('NATIVE', 'Native American'), ('HAWAIIAN/PACIFIC_ISLANDER', 'Native Hawaiian/Pacific Islander'), ('WHITE', 'White'), ('OTHER', 'Other'), ('', '-------')], max_length=50),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('', '-------')], max_length=1),
        ),
    ]
