# Generated by Django 2.0.1 on 2018-02-21 11:47

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20180214_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='location',
            field=address.models.AddressField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.Address'),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='employer_address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_employer_address', to='address.Address'),
        ),
        migrations.AlterField(
            model_name='incidentinvolvedparty',
            name='home_address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_home_address', to='address.Address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
