# Generated by Django 2.0.1 on 2018-02-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20180221_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentinvolvedparty',
            name='display_sequence',
            field=models.IntegerField(null=True),
        ),
    ]
