version: 2
jobs:
  build:
    working_directory: ~/APDIncidentReports
    docker:
      - image: circleci/python:3.7.2
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:11.3
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev_env.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            coverage run --source='.' manage.py test
            coverage report -m

      - store_artifacts:
          path: test-reports
          destination: test-reports
